name: Send Email on Schedule

on:
  schedule:
    # This runs every day at 04:00 UTC (9:30 AM IST)
    - cron: '8 13 * * *'
  workflow_dispatch: # This adds a manual "Play" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python send_email.py
